### ISSUE TITLE
Vscode seems to default to dist/index.js version of this lib 

### ISSUE THREAD

**Issue by hixus** [Turee/koa-yup-validator#17]
Vscode seems to default to dist/index.js version of this lib. Not sure if this a bug or configuration issue. Would be nice to get the typings as I can see that this is developed with typescript.

**Comment by hixus** [comment]
ok, created a pr https://github.com/Turee/koa-yup-validator/pull/19

**Comment by Turee** [comment]
Merged, thanks @hixus .
